-- AlterTable
ALTER TABLE "User" ADD COLUMN "roadBestScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "totalCoinPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "totalCoinsCollected" INTEGER NOT NULL DEFAULT 0;
