/** 100 humiliating game-over roasts — pick one at random on lose. */
export const HUMILIATING_LINES: string[] = [
  "You got absolutely fucking flattened.",
  "That car had a personal vendetta and you lost.",
  "Skill issue. Catastrophic skill issue.",
  "Even the traffic cones are laughing at you.",
  "You call that crossing? Pathetic.",
  "The road just filed a restraining order.",
  "Bro really thought he was the main character.",
  "Your reflexes are on unpaid leave.",
  "Hit by a car in a game. Peak fucking performance.",
  "The vehicles weren't even trying.",
  "You died like a tutorial NPC.",
  "That was embarrassing for everyone watching.",
  "Crossy Road just unfollowed you.",
  "Your score is a cry for help.",
  "Were your eyes closed or just decorative?",
  "The chain deserved a better partner.",
  "You got smoked. Literally almost.",
  "Cars: 1. Your dignity: 0.",
  "That hop looked like a medical emergency.",
  "You've been demoted to sidewalk resident.",
  "Fucking legendary fail. Screenshot that.",
  "The truck waved. You still lost.",
  "Are you allergic to not dying?",
  "Your timing is a war crime.",
  "Even the grass is disappointed.",
  "You moved like you owed the asphalt money.",
  "That wasn't unlucky. That was you.",
  "Pro tip: don't stand in front of cars. Wild concept.",
  "Your funeral playlist is just beep beep.",
  "The AI drivers feel bad for you. That's sad.",
  "You got owned harder than a free parking spot.",
  "Congratulations, you're roadkill cosplay.",
  "Did you mean to lose or is this your strat?",
  "The fuck was that hop?",
  "You peaked at pressing Start.",
  "Traffic just clapped. Not for you.",
  "Your ancestors unsubscribed.",
  "That score belongs in a museum of shame.",
  "You died faster than my patience.",
  "Even the loading screen lasted longer than you.",
  "Absolute clown shoes energy.",
  "The car didn't hit you. You hit rock bottom.",
  "You're why crosswalks have buttons.",
  "Fuck around and find out — you found out.",
  "That was a masterclass in how not to play.",
  "Your thumbs need a refund.",
  "The road said 'not today, dumbass.'",
  "You got yeeted into the shadow realm.",
  "Skill? Never heard of her.",
  "You're the reason pause exists — to cry.",
  "That chain is filing for divorce.",
  "Partner deserved better. The cars agree.",
  "You lost so hard the fog cleared out of pity.",
  "Were you speedrunning humiliation?",
  "The horn was your theme song.",
  "You just invented a new way to suck.",
  "Fucking spectacular failure. Almost art.",
  "Your IQ left the chat mid-hop.",
  "The truck collected you like pocket change.",
  "Try looking both ways. Or any ways.",
  "You're not cursed. You're just bad.",
  "That death was sponsored by poor decisions.",
  "Even bot drivers have more aura.",
  "You got bodybagged by a box with wheels.",
  "Respectfully, delete the game.",
  "Disrespectfully, delete the game.",
  "Your high score is a participation trophy.",
  "The asphalt tasted victory today.",
  "You hopped into destiny. Destiny was a bumper.",
  "Bro fell off before he got on.",
  "That was less 'crossing' and more 'collapsing.'",
  "Cars aren't the problem. You are.",
  "You've been served. Hot. Fresh. Flattened.",
  "Fuck my life — wait, no: fuck YOUR life.",
  "The game over screen was lonely without you. Not anymore.",
  "You made losing look effortless. Congrats?",
  "Your coordination called. It's broken.",
  "Even Comic Sans had more structure than that run.",
  "You got mid-diffed by traffic.",
  "That wasn't a run. That was a crime scene.",
  "Please touch grass. Then avoid cars on it.",
  "Your ghost is already getting hit again.",
  "The universe whispered 'nope.'",
  "You died with the confidence of a genius. Incorrectly.",
  "Absolute fucking disaster. 10/10 comedy.",
  "The chain swung. You missed life.",
  "You're the DLC nobody asked for: Failure Pack.",
  "Hit detection worked. Your brain didn't.",
  "You vs car: car booked the W in advance.",
  "That score is smaller than your excuses.",
  "You've unlocked: Chronic Embarrassment.",
  "The road rolled a crit. You rolled a 1.",
  "Stop hopping like you're late to your own funeral.",
  "You got clapped so hard the camera shook for real.",
  "Legendary L. Frame it.",
  "Your thumbs are committing vehicular manslaughter — on you.",
  "Even the retry button is secondhand embarrassed.",
  "You lost the plot and the pavement.",
  "Fucking tragic. Beautifully tragic.",
  "You didn't cross the road. The road crossed you.",
];

export function pickHumiliatingLine(exclude?: string): string {
  if (HUMILIATING_LINES.length === 0) return "You lost. Somehow.";
  let line = HUMILIATING_LINES[Math.floor(Math.random() * HUMILIATING_LINES.length)];
  if (exclude && HUMILIATING_LINES.length > 1) {
    let guard = 0;
    while (line === exclude && guard < 8) {
      line = HUMILIATING_LINES[Math.floor(Math.random() * HUMILIATING_LINES.length)];
      guard += 1;
    }
  }
  return line;
}

export const HUMILIATING_COUNT = HUMILIATING_LINES.length;
