// characters.js — Crossy-style voxel animals + extras

export const characters = {
  chicken: {
    id: "chicken",
    name: "Chicken",
    icon: "🐔",
    description: "The classic road-crosser",
    style: "voxel",
    species: "chicken",
    colors: {
      body: 0xffffff,
      accent: 0xe53935,
      beak: 0xffc107,
      legs: 0xff9800,
      eyes: 0x111111,
    },
  },
  chick: {
    id: "chick",
    name: "Chick",
    icon: "🐤",
    description: "Tiny yellow floof",
    style: "voxel",
    species: "chick",
    colors: {
      body: 0xffeb3b,
      accent: 0xffc107,
      beak: 0xff9800,
      legs: 0xff9800,
      eyes: 0x111111,
    },
  },
  elephant: {
    id: "elephant",
    name: "Elephant",
    icon: "🐘",
    description: "Big ears, bigger vibes",
    style: "voxel",
    species: "elephant",
    colors: {
      body: 0x9e9e9e,
      accent: 0x757575,
      tusks: 0xfafafa,
      eyes: 0x111111,
    },
  },
  penguin: {
    id: "penguin",
    name: "Penguin",
    icon: "🐧",
    description: "Formal and fabulous",
    style: "voxel",
    species: "penguin",
    colors: {
      body: 0x212121,
      belly: 0xffffff,
      beak: 0xffc107,
      feet: 0xff9800,
      eyes: 0x111111,
    },
  },
  cardinal: {
    id: "cardinal",
    name: "Cardinal",
    icon: "🐦",
    description: "Red and ready",
    style: "voxel",
    species: "cardinal",
    colors: {
      body: 0xe53935,
      mask: 0x111111,
      beak: 0xffc107,
      crest: 0xc62828,
      eyes: 0x111111,
    },
  },
  panda: {
    id: "panda",
    name: "Panda",
    icon: "🐼",
    description: "Bamboo bandit",
    style: "voxel",
    species: "panda",
    colors: {
      body: 0xffffff,
      black: 0x212121,
      eyes: 0x111111,
    },
  },
  moose: {
    id: "moose",
    name: "Moose",
    icon: "🫎",
    description: "Antler royalty",
    style: "voxel",
    species: "moose",
    colors: {
      body: 0xa1887f,
      antler: 0x8d6e63,
      nose: 0x3e2723,
      eyes: 0x111111,
    },
  },
  rhino: {
    id: "rhino",
    name: "Rhino",
    icon: "🦏",
    description: "Horn first, questions later",
    style: "voxel",
    species: "rhino",
    colors: {
      body: 0x90a4ae,
      horn: 0xcfd8dc,
      eyes: 0x111111,
    },
  },
  frog: {
    id: "frog",
    name: "Frog",
    icon: "🐸",
    description: "Hop royalty",
    style: "voxel",
    species: "frog",
    colors: {
      body: 0x66bb6a,
      belly: 0xc5e1a5,
      eyes: 0x111111,
    },
  },
  pig: {
    id: "pig",
    name: "Pig",
    icon: "🐷",
    description: "Snout and about",
    style: "voxel",
    species: "pig",
    colors: {
      body: 0xf8bbd0,
      snout: 0xf48fb1,
      eyes: 0x111111,
    },
  },
  dog: {
    id: "dog",
    name: "Dog",
    icon: "🐶",
    description: "Good boy energy",
    style: "voxel",
    species: "dog",
    colors: {
      body: 0xffcc80,
      ear: 0xef6c00,
      nose: 0x212121,
      eyes: 0x111111,
    },
  },
  cow: {
    id: "cow",
    name: "Cow",
    icon: "🐮",
    description: "Mooove it",
    style: "voxel",
    species: "cow",
    colors: {
      body: 0xffffff,
      spot: 0x212121,
      nose: 0xf8bbd0,
      eyes: 0x111111,
    },
  },
  ali: {
    id: "ali",
    name: "علی",
    icon: "🧔",
    description: "علی",
    texture: "/characters/ali-head.png",
    cubeSize: [24, 24, 28],
    colors: {
      body: 0xffffff,
      cap: 0xffffff,
      eyes: 0x000000,
    },
    style: "textured",
  },
};

export const defaultCharacter = "chicken";
